### ISSUE TITLE
Incorrect trace of x64 instructions with RIP-relative addressing

### ISSUE THREAD

**Issue by HexKitchen** [synacktiv/frinet#3]
When tracing memory accesses, the wrong addresses are recorded when an x64 instruction uses RIP-relative addressing. RIP-relative addressing is special, because the base address is not the current value of `@rip` (as it would be for other registers), but rather "next" value of `@rip`, meaning the address of the subsequent instruction in memory order.

Besides the incorrect trace data, this can cause a crash if the incorrectly-computed address is not accessible (which, honestly, is how I noticed this problem). To repro on Windows, compile a "Hello world" executable using VC and trace the `main` function.

**Comment by myr-syn** [comment]
Thank you for your contribution!
